#!/bin/bash

set -e

platform=`uname`

is_installed() {
  if [[ -z "$(which $1)" ]]; then
    return 1
  fi

  return 0
}

ensure_installed() {
  if is_installed $1; then
    return 0
  fi

  if is_installed apt-get; then
    if [[ -z "$APT_UPDATED" ]]; then
      apt-get update
      export APT_UPDATED=1
    fi
    apt-get install $1 -y
  elif is_installed brew; then
    brew update && brew install $1
  else
    echo "Can't manually install $1, please make sure $1 is installed and restart again"
    exit 1
  fi
}

# these tools should be already present on mac
ensure_installed zsh
ensure_installed git
ensure_installed curl

cd $HOME
git clone https://github.com/g13013/env-bootstrap.git
cd env-bootstrap
curl https://raw.githubusercontent.com/g13013/env-bootstrap/master/install-prezto | zsh
curl https://raw.githubusercontent.com/g13013/env-bootstrap/master/install-dev-tools | bash

tee ~/.zmodules <<EOF
zstyle ':prezto:load' pmodule \\
  'fasd' \\
  'archive' \\
  'autosuggestions' \\
  'rsync' \\
  'tmux' \\
  'git' \\
  'environment' \\
  'terminal' \\
  'editor' \\
  'history' \\
  'directory' \\
  'spectrum' \\
  'utility' \\
  'completion' \\
  'prompt'
EOF

echo "[[ -f ~/.zmodules ]] && source ~/.zmodules" | tee -a ~/.zshrc

ensure_installed fasd