#!/bin/zsh

INSTALL_SOURCE=${INSTALL_SOURCE:-"https://raw.githubusercontent.com/g13013/env-bootstrap/master"}

set -e

# load helpers
[[ -z $(which curl) ]] &&  apt-get update && apt-get install curl -y
curl -ssL  $INSTALL_SOURCE/install_helpers > /tmp/install_helpers && source /tmp/install_helpers || (echo "Can't load helpers file from $INSTALL_SOURCE/install_helpers" && exit 1)

! is_installed git && (on_mac && install_xcode || ensure_installed git) # git is special, on mac we prioritize xcode git version

if [[ ! -e "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
else
  log "zprezto already installed"
fi

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  if [[ -f "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
    warn "${ZDOTDIR:-$HOME}/.${rcfile:t} already exists, not copying"
  else
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  fi
done

log "Installing zprezto modules"
warn "    wakatime"
mkdir -p ~/.zprezto/modules/wakatime &&
  (curl -sSL https://raw.githubusercontent.com/wbinglee/zsh-wakatime/master/zsh-wakatime.plugin.zsh | tee ~/.zprezto/modules/wakatime/init.zsh) 1>/dev/null
warn "    zsh-cwd-history"
mkdir -p ~/.zprezto/modules/zsh-cwd-history &&
  (curl  -sSL https://raw.githubusercontent.com/ericfreese/zsh-cwd-history/master/zsh-cwd-history.zsh | tee ~/.zprezto/modules/zsh-cwd-history/init.zsh) 1>/dev/null

if [ "$(get_shell)" != "zsh" ]; then
  warn "your actual shell is $_info$(get_shell)$_reset"
  log "Need you to type your password to set ${_info}zsh${_reset} as your default prompt"
  chsh -s /bin/zsh
fi
