#!/bin/zsh

set -e

platform=`uname`

ensure_installed() {
  if is_installed $1; then
    return 0
  fi

  if is_installed apt-get; then
    apt-get update && apt-get install $1 -y
  else
    echo "Please make sure git and curl are installed"
    exit 1
  fi
}

function is_installed {
  if [[ -z "$(which $1)" ]]; then
    return 1
  fi

  return 0
}

ensure_installed git
ensure_installed curl

git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"

setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  if [[ -f "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]]; then
    echo "${ZDOTDIR:-$HOME}/.${rcfile:t} already exists, not copying"
  else
    ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
  fi
done

chsh -s /bin/zsh
