#!/bin/bash

if [[ "`uname`" == 'Linux' ]] && [[ $UID != 0 ]]; then
    echo "Please run this script with sudo to be able to install packages"
    exit 1
fi

INSTALL_SOURCE=${INSTALL_SOURCE:-"https://raw.githubusercontent.com/g13013/env-bootstrap/master"}

set -e

# load helpers
[[ -z $(which curl) ]] &&
  (
    echo -e "\x1B[0;32mInstalling curl...\033[0m" && apt-get update && apt-get install curl -y && export PKG_UPDATED=1 ||
    echo -e "\x1B[0;31mInstalling curl failed\033[0m"
  )

curl -ssL  $INSTALL_SOURCE/install_helpers > /tmp/install_helpers && source /tmp/install_helpers || (echo "Can't load helpers file from $INSTALL_SOURCE/install_helpers" && exit 1)

! is_installed git && (on_mac && install_xcode || ensure_installed git) # git is special, on mac we prioritize xcode git version


ensure_installed zsh

curl -sSL ${INSTALL_SOURCE}/install-prezto | INSTALL_SOURCE=$INSTALL_SOURCE zsh
curl -sSL ${INSTALL_SOURCE}/install-dev-tools | INSTALL_SOURCE=$INSTALL_SOURCE bash

log "Configuring zprezto (zsh)"
[ ! -f ~/.zmodules ] && (curl -sSL ${INSTALL_SOURCE}/zmodules | tee ~/.zmodules 1>/dev/null) || warn '~/.zmodules already exists, ignoring'
([ ! -e ~/.zpreztorc ] ||  [ -L ~/.zpreztorc ]) && (curl -sSL ${INSTALL_SOURCE}/zpreztorc | tee ~/.zpreztorc 1>/dev/null) || warn '~/.zpreztorc already exists, ignoring'

if ! is_installed fasd && on_linux; then
  log "Installing fasd prerequisites"

  if ! is_installed add-apt-repository; then
    ensure_installed software-properties-common
    ensure_installed python-software-properties
  fi

  add-apt-repository ppa:aacebedo/fasd -y 1>/dev/null
  apt-get update
fi

ensure_installed fasd

warn
warn "Tweak your list of zprezto modules to load in ~/.zmodules"
warn
